### ISSUE TITLE
Donate to Apache?

### ISSUE THREAD

**Issue by jimjag** [roadrunner2/mod-proxy-protocol#1]
Any interest in donating this module to the ASF for inclusion in the official repo of Apache httpd?

**Comment by roadrunner2** [comment]
Yes, we would be happy to do so. What would you need from me?

**Comment by jimjag** [comment]
That would be very cool! You could either donate it formally via the Software Grant (https://www.apache.org/licenses/software-grant.txt) or you could simply send me an email, with your permission (since it is ALv2 licensed) to "fork" a copy into the ASF repo. Whichever is easier for you.

**Comment by systeminsightsbuild** [comment]
Did this ever get donated/integrated into official Apache httpd?

**Comment by roadrunner2** [comment]
Not yet. I'll update here when I have more info.

**Comment by memelet** [comment]
Ok, I was able to build and use no problem.

**Comment by LoicGombeaud** [comment]
This module works very well for me, and I would very much like to see it in the official ASF repo!

**Comment by jimjag** [comment]
Just quickly checking again if it would be OK to fold this into the official ASF repo, with the required NOTICE info, of course. That way we could track it with mod_http2 and the other protocols we are using.  Thx!!

**Comment by roadrunner2** [comment]
Folding this into the ASF repo would be great!

**Comment by jimjag** [comment]
roadrunner2 that is great news! I will take the current version and copy it into trunk, with full acknowledgement of your donation and copyright.

Thanks!!

**Comment by alexbowers** [comment]
@jimjag Is this in Apache 2.4 or 2.5?

**Comment by jimjag** [comment]
This is currently in 2.5 and being backported to 2.4 as part of the mod_remoteip module.

**Comment by alexbowers** [comment]
So how would I be best to use it currently?

**Comment by roadrunner2** [comment]
@alexbowers If are running a version of httpd that does not have this module, then just clone this repo and build it yourself as described in the README.
