### ISSUE TITLE
undefined symbol: apr_sockaddr_is_wildcard

### ISSUE THREAD

**Issue by humayunghani** [roadrunner2/mod-proxy-protocol#7]
I installed it with apxs...
`sudo apxs -c -i mod_proxy_protocol.c`

And then loaded the module but "`sudo httpd -t`" throws this error:

> _httpd: Syntax error on line 56 of /etc/httpd/conf/httpd.conf: Syntax error on line 7 of /etc/httpd/conf.modules.d/00-proxy.conf: Cannot load modules/mod_proxy_protocol.so into server: /etc/httpd/modules/mod_proxy_protocol.so: undefined symbol: apr_sockaddr_is_wildcard_

Can you help me how to fix this error? 
I'm using CentOS 7...
> Linux ip-10-0-0-233 3.10.0-229.20.1.el7.x86_64 #1 SMP Tue Nov 3 19:10:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

`httpd -v`

> Server version: Apache/2.4.6 (CentOS)
> Server built:   Nov 14 2016 18:04:44

**Comment by yhojann-cl** [comment]
Same problem.

**Comment by humayunghani** [comment]
I'm also not able to fix it yet. Still waiting someone could help us on this. I think I should use this instead: https://github.com/ggrandes/apache24-modules

**Comment by praveenkpatidar** [comment]
We are also looking for some solution. We are having same issue. 
Linux RHEL7, 
Installed gcc httpd-devel
clone repo, run  'apxs -c -i mod_proxy_protocol.c'
LoadModule statement. 
http -t gives same output.

**Comment by roadrunner2** [comment]
Fixed now.
